Q1 Write a program to generate a 6-digit random secure OTP

In [6]:
import random

characters = 'ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz0123456789'

# Generate OTP
otp = ''
for _ in range(6):
    otp += random.choice(characters)

print("Original OTP:", otp)

# Caesar cipher shift value
shift = 3

def caesar_encrypt(text, shift):
    encrypted = ''
    for char in text:
        if char.isdigit():
            # Shift digits (0-9)
            encrypted += str((int(char) + shift) % 10)
        elif char.isalpha():
            # Shift letters
            if char.isupper():
                base = ord('A')
            else:
                base = ord('a')
            # Shift within alphabet
            encrypted += chr((ord(char) - base + shift) % 26 + base)
        else:
            # For any other character (if any), keep as is
            encrypted += char
    return encrypted

def caesar_decrypt(text, shift):
    return caesar_encrypt(text, -shift)

# Encrypt OTP
encrypted_otp = caesar_encrypt(otp, shift)
print("Encrypted OTP:", encrypted_otp)

# Decrypt OTP (to verify)
decrypted_otp = caesar_decrypt(encrypted_otp, shift)
print("Decrypted OTP:", decrypted_otp)


Original OTP: GufjMe
Encrypted OTP: JximPh
Decrypted OTP: GufjMe


Q2. Write a program to pick a random character from a user-supplied string

In [7]:
import random

user_input = input("Enter a string: ")
random_char = random.choice(user_input)

print("Random character is:", random_char)


Random character is: e


Q3. Write a program to generate a random password that meets the following conditions:<br/>
a. Password length must be 10 characters long.<br/>
b. It must contain at least 2 uppercase letters, 1 digit, and 1 special symbol.

In [ ]:
import random

uppercase = 'ABCDEFGHIJKLMNOPQRSTUVWXYZ'
lowercase = 'abcdefghijklmnopqrstuvwxyz'
digits = '0123456789'
symbols = '!@#$%&*?'

# Required characters
password = [
    random.choice(uppercase),
    random.choice(uppercase),
    random.choice(digits),
    random.choice(symbols)
]

# Fill remaining characters
all_chars = uppercase + lowercase + digits + symbols
for i in range(6):
    password.append(random.choice(all_chars))

# Shuffle to mix the characters
random.shuffle(password)

# Join and print
print("Generated Password:", ''.join(password))


Generated Password: $sam2samGsam8sam7samRsamhsamrsam!samP


Q4. Given two lists of numbers, write a program to create a new list containing odd
numbers from the first list and even numbers from the second list.

In [9]:
# Example input lists
list1 = [1, 2, 3, 4, 5]
list2 = [10, 11, 12, 13, 14]

# Extract odd from list1
odd_from_list1 = [x for x in list1 if x % 2 != 0]

# Extract even from list2
even_from_list2 = [x for x in list2 if x % 2 == 0]

# Combine both
result = odd_from_list1 + even_from_list2

# Output result
print("Resulting list:", result)


Resulting list: [1, 3, 5, 10, 12, 14]


Q5. Write a program to create a numpy array and return an array of odd rows and even
columns from the numpy array.

In [12]:
import numpy as np

arr = np.arange(1, 37).reshape(6, 6)

print("Original Array:")
print(arr)

result = arr[1::2, ::2]

print("\nOdd Rows and Even Columns:")
print(result)


Original Array:
[[ 1  2  3  4  5  6]
 [ 7  8  9 10 11 12]
 [13 14 15 16 17 18]
 [19 20 21 22 23 24]
 [25 26 27 28 29 30]
 [31 32 33 34 35 36]]

Odd Rows and Even Columns:
[[ 7  9 11]
 [19 21 23]
 [31 33 35]]


Q6 Write a program to create a numpy array and sort it as per the following cases:<br/>
a. Case 1: Sort the array by the second row.</br>
b. Case 2: Sort the array by the second column

In [13]:
import numpy as np

# Create a sample 2D numpy array
arr = np.array([[34, 12, 25],
                [88, 55, 66],
                [91, 11, 45]])

print("Original Array:")
print(arr)

sorted_indices_row = np.argsort(arr[1])
sorted_by_second_row = arr[:, sorted_indices_row]

print("\nArray Sorted by Second Row:")
print(sorted_by_second_row)

sorted_indices_col = np.argsort(arr[:, 1])
sorted_by_second_col = arr[sorted_indices_col]

print("\nArray Sorted by Second Column:")
print(sorted_by_second_col)


Original Array:
[[34 12 25]
 [88 55 66]
 [91 11 45]]

Array Sorted by Second Row:
[[12 25 34]
 [55 66 88]
 [11 45 91]]

Array Sorted by Second Column:
[[91 11 45]
 [34 12 25]
 [88 55 66]]
